### ISSUE TITLE
AttributeError while parsing chezmoi arguments

### ISSUE THREAD

**Issue by NavyD** [NavyD/dotfiles#11]
```sh
$ cz apply ~/.config/zsh/config
Traceback (most recent call last):
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 153, in <module>
    main()
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 136, in main
    if args.has_debug() or args.has_verbose():
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/util.py", line 148, in has_verbose
    opts = self._sub_opts.split()
AttributeError: 'NoneType' object has no attribute 'split'
chezmoi: exit status 1
```

**Comment by NavyD** [comment]
```sh
$ cz diff
Traceback (most recent call last):
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 153, in <module>
    main()
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 144, in main
    check_passhole(args)
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 83, in check_passhole
    if path.is_dir():
AttributeError: 'NoneType' object has no attribute 'is_dir'
chezmoi: exit status 1

```
