### ISSUE TITLE
Require passhole password only if file contains passhole template

### ISSUE THREAD

**Issue by NavyD** [NavyD/dotfiles#8]

**Comment by NavyD** [comment]
```sh
x cz diff -v /home/navyd/.autorestic.env /home/navyd/.autorestic.lock.yml /home/navyd/.autorestic.yml 
parsed chezmoi {'_subcommand': 'diff', '_target_paths': {PosixPath('/home/navyd/.autorestic.yml'), PosixPath('/home/navyd/.autorestic.lock.yml'), PosixPath('/home/navyd/.autorestic.env')}, '_is_debug': False, '_is_verbose': True, '_data': None} for args `chezmoi diff -v /home/navyd/.autorestic.env /home/navyd/.autorestic.lock.yml /home/navyd/.autorestic.yml`
Traceback (most recent call last):
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 155, in <module>
    main()
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 146, in main
    check_passhole(args)
  File "/home/navyd/.local/share/chezmoi/vendor/dotutil/pre.py", line 85, in check_passhole
    if path.is_dir():
AttributeError: 'filter' object has no attribute 'is_dir'
chezmoi: exit status 1
```
